#!/usr/bin/env bash
# Generated by OASIS. Simulates the design with the OASIS testbench using Verilator (>= 5).
# Run from anywhere: bash @@SIM_DIR@@/run_verilator.sh
# Writes sim.log (cycle count) and mem_N.out (memory contents after the run) here.
# Verilator compiles the RTL to C++ first (verilator_build.log); that step is slow for
# large designs but the simulation itself is much faster than xsim.
set -euo pipefail
cd "$(dirname "$0")"
rm -f mem_*.out

# Same flags as Calyx's fud2 (verilator.rhai): --binary implies --timing (needed for the
# testbench clock); -fno-inline keeps the hierarchy that $readmemh(mem_N.mem) refers to.
# -j 0: compile the generated C++ with all cores.  TODO(verify): -j 0 needs Verilator >= 5.
"@@VERILATOR@@" "@@DESIGN_SV@@" tb.sv --trace --binary --top-module toplevel -fno-inline \
  -Wno-fatal -j 0 -Mdir verilator_obj > verilator_build.log 2>&1 \
  || { echo "verilator build failed; see $PWD/verilator_build.log" >&2; exit 1; }

./verilator_obj/Vtoplevel \
  "+DATA=$PWD" \
  "+CYCLE_LIMIT=${CYCLE_LIMIT:-@@CYCLE_LIMIT@@}" \
  "+NOTRACE=${NOTRACE:-1}" 2>&1 | tee sim.log
