#!/usr/bin/env bash
# Generated by OASIS. Vivado batch synthesis; writes utilization.rpt and timing.rpt here.
# Run from anywhere: bash @@SYNTH_DIR@@/run_synth.sh
set -euo pipefail
cd "$(dirname "$0")"
"@@VIVADO@@" -mode batch -nojournal -log synth.log -source synth.tcl
