#!/usr/bin/env bash
# Generated by OASIS. Simulates the design with the OASIS testbench in Vivado xsim.
# Run from anywhere: bash @@SIM_DIR@@/run_xsim.sh
# Writes sim.log (cycle count) and mem_N.out (memory contents after the run) here.
set -euo pipefail
cd "$(dirname "$0")"
rm -f mem_*.out

# Flags verified with Vivado 2023.2 (2026-10-02).
"@@XVLOG@@" --sv "@@DESIGN_SV@@" tb.sv --log xvlog.log
"@@XELAB@@" toplevel --snapshot oasis_tb --timescale 1ns/1ps --log xelab.log
"@@XSIM@@" oasis_tb --runall --log sim.log \
  --testplusarg "DATA=$PWD" \
  --testplusarg "CYCLE_LIMIT=${CYCLE_LIMIT:-@@CYCLE_LIMIT@@}" \
  --testplusarg "NOTRACE=${NOTRACE:-1}"
