#!/usr/bin/env bash
# Generated by OASIS. Yosys synthesis; writes stat.json (cell counts) and yosys.log here.
# Run from anywhere: bash @@SYNTH_DIR@@/run_yosys.sh
set -euo pipefail
cd "$(dirname "$0")"
rm -f stat.json
"@@YOSYS@@" -q -l yosys.log -s synth.ys
