# Generated by OASIS. Out-of-context synthesis of `@@TOP@@` on @@PART@@ at @@CLOCK_MHZ@@ MHz.
# The kernel's memories are ports (address/data/enable), like an HLS kernel with memory
# interfaces, so the reports cover the datapath and control, not the A/B/C storage.
read_verilog -sv @@DESIGN_SV@@
read_xdc clocks.xdc
synth_design -top @@TOP@@ -part @@PART@@ -mode out_of_context
report_utilization -file utilization.rpt
report_timing_summary -file timing.rpt
