// Generated by OASIS. Testbench for a Calyx-generated design (top module `main`).
// Based on the Calyx fud2 testbench (calyx/fud2/rsrc/tb.sv, MIT license).
//
// The design loads its memories from $readmemh({DATA, "/mem_N.dat"}) at time 0 and dumps
// them to mem_N.out in its `final` block, which runs when this testbench calls $finish.
//
// Plusargs:
//   +DATA=<dir>          directory with mem_N.dat (read by the design)
//   +CYCLE_LIMIT=<n>     stop after n cycles (default @@CYCLE_LIMIT@@)
//   +NOTRACE=0           enable VCD tracing (default off)
//   +OUT=<file.vcd>      VCD file name (default trace.vcd)
`timescale 1ns / 1ps

module toplevel;

  localparam real HALF_PERIOD_NS = @@HALF_PERIOD_NS@@;  // @@CLOCK_MHZ@@ MHz
  localparam int RESET_CYCLES = @@RESET_CYCLES@@;

  logic go, done, clk, reset;

  main main (
      .go(go),
      .clk(clk),
      .reset(reset),
      .done(done)
  );

  longint cycle_count;
  longint CYCLE_LIMIT;
  int NOTRACE;
  string OUT;
  int CODE;

  initial begin
    clk = 0;
    reset = 1;
    go = 0;
    cycle_count = 0;

    CYCLE_LIMIT = @@CYCLE_LIMIT@@;
    CODE = $value$plusargs("CYCLE_LIMIT=%d", CYCLE_LIMIT);
    NOTRACE = 1;
    CODE = $value$plusargs("NOTRACE=%d", NOTRACE);
    if (NOTRACE == 0) begin
      OUT = "trace.vcd";
      CODE = $value$plusargs("OUT=%s", OUT);
      $display("VCD tracing enabled: %s", OUT);
      $dumpfile(OUT);
      $dumpvars(0, main);
    end
  end

  always #(HALF_PERIOD_NS) clk = ~clk;

  // Plain `always`, not `always_ff`: these signals are also initialised in the `initial`
  // block above, and xsim rejects an always_ff variable with any other driver (VRFC 10-3818).
  always @(posedge clk) begin
    cycle_count <= cycle_count + 1;
    if (cycle_count < RESET_CYCLES) begin
      reset <= 1;
      go <= 0;
    end else begin
      reset <= 0;
      go <= 1;
    end
  end

  always @(negedge clk) begin
    if (cycle_count > RESET_CYCLES && done == 1) begin
      // cycle_count was incremented at the end of the cycle in which done rose.
      $display("Simulated %0d cycles", cycle_count - RESET_CYCLES - 1);
      $finish;
    end else if (cycle_count >= CYCLE_LIMIT + RESET_CYCLES) begin
      $display("TIMEOUT: reached limit of %0d cycles without done", CYCLE_LIMIT);
      $finish;
    end
  end

endmodule
